# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import route_pb2 as src_dot_route__pb2


class VCGatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VoiceChange = channel.unary_unary(
            '/VCGateway/VoiceChange',
            request_serializer=src_dot_route__pb2.VCRequest.SerializeToString,
            response_deserializer=src_dot_route__pb2.VCResponse.FromString,
        )


class VCGatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VoiceChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VCGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'VoiceChange': grpc.unary_unary_rpc_method_handler(
            servicer.VoiceChange,
            request_deserializer=src_dot_route__pb2.VCRequest.FromString,
            response_serializer=src_dot_route__pb2.VCResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'VCGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))

 # This class is part of an EXPERIMENTAL API.


class VCGateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VoiceChange(request,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
        return grpc.experimental.unary_unary(request, target, '/VCGateway/VoiceChange',
                                             src_dot_route__pb2.VCRequest.SerializeToString,
                                             src_dot_route__pb2.VCResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
