# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/route.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsrc/route.proto\"O\n\x12StreamingVCRequest\x12\"\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x12.StreamingVCConfig\x12\x15\n\raudio_content\x18\x02 \x01(\x0c\"$\n\x11StreamingVCConfig\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\"?\n\x13StreamingVCResponse\x12\x15\n\raudio_content\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\t2K\n\tVCGateway\x12>\n\x0bStreamingVC\x12\x13.StreamingVCRequest\x1a\x14.StreamingVCResponse\"\x00(\x01\x30\x01\x62\x06proto3')



_STREAMINGVCREQUEST = DESCRIPTOR.message_types_by_name['StreamingVCRequest']
_STREAMINGVCCONFIG = DESCRIPTOR.message_types_by_name['StreamingVCConfig']
_STREAMINGVCRESPONSE = DESCRIPTOR.message_types_by_name['StreamingVCResponse']
StreamingVCRequest = _reflection.GeneratedProtocolMessageType('StreamingVCRequest', (_message.Message,), {
  'DESCRIPTOR' : _STREAMINGVCREQUEST,
  '__module__' : 'src.route_pb2'
  # @@protoc_insertion_point(class_scope:StreamingVCRequest)
  })
_sym_db.RegisterMessage(StreamingVCRequest)

StreamingVCConfig = _reflection.GeneratedProtocolMessageType('StreamingVCConfig', (_message.Message,), {
  'DESCRIPTOR' : _STREAMINGVCCONFIG,
  '__module__' : 'src.route_pb2'
  # @@protoc_insertion_point(class_scope:StreamingVCConfig)
  })
_sym_db.RegisterMessage(StreamingVCConfig)

StreamingVCResponse = _reflection.GeneratedProtocolMessageType('StreamingVCResponse', (_message.Message,), {
  'DESCRIPTOR' : _STREAMINGVCRESPONSE,
  '__module__' : 'src.route_pb2'
  # @@protoc_insertion_point(class_scope:StreamingVCResponse)
  })
_sym_db.RegisterMessage(StreamingVCResponse)

_VCGATEWAY = DESCRIPTOR.services_by_name['VCGateway']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STREAMINGVCREQUEST._serialized_start=19
  _STREAMINGVCREQUEST._serialized_end=98
  _STREAMINGVCCONFIG._serialized_start=100
  _STREAMINGVCCONFIG._serialized_end=136
  _STREAMINGVCRESPONSE._serialized_start=138
  _STREAMINGVCRESPONSE._serialized_end=201
  _VCGATEWAY._serialized_start=203
  _VCGATEWAY._serialized_end=278
# @@protoc_insertion_point(module_scope)
